### ISSUE TITLE
Allow running on newer versions of IntelliJ (eg 2022.1 EAP)

### ISSUE THREAD

**Issue by seanf** [Netflix/dgs-intellij-plugin#27]
The value `pluginUntilBuild=213.*` in `gradle.properties` is restricting the plugin to IntelliJ <= 2021.3, which means the plugin can't be installed into IntelliJ 2022.1 EAP. 

Are there any expected compatibility concerns? Would it be possible to increase the version, or even avoid setting an upper version?

**Comment by seanf** [comment]
FWIW, I've been using it (locally built) on the EAP (and now the Beta) for weeks with no sign of a problem.

**Comment by srinivasankavitha** [comment]
Thanks for verifying that. I will update and prepare a release likely next
week. There are a few more fixes that I would like to get in as well before
that.

**Comment by seanf** [comment]
This is also a problem with IntelliJ 2022.2 which was just released.

**Comment by srinivasankavitha** [comment]
Thanks! We are in the process of fixing and releasing.

**Comment by liias** [comment]
IDEA upgrade prompt for `2022.3` reports the plugin as incompatible as well.

**Comment by srinivasankavitha** [comment]
This is addressed and fixed.
