### ISSUE TITLE
DGS plugin gives a warning saying collectionType value set as input does not match the schema

### ISSUE THREAD

**Issue by vasquez-csdisco** [Netflix/dgs-intellij-plugin#29]
Hi,

I am getting a warning message when implementing a @DgsData function that contains a method inside. 

Script example:

```
type Data @key(fields: "id") @extends{
  id: ID! @external
  configurations(settings: [ConfigInput!]!): [ConfigOutput!]!
}

input ConfigInput {
  name: String!
}

type ConfigOutput {
  value: String!
}
```
And implementing this method

```
 @DgsData(parentType = "Data", field = "configurations")
  fun type1Configurations(@InputArgument(collectionType = ConfigInput::class) settings: List<ConfigInput>): List<ConfigurationToggle> {

    // Work here
  }
```

I keep getting a warning saying that `@InputArgument type does not match the schema, expected @InputArgument (collectionType=ConfigInput) settings: List<ConfigInput> `

If I apply the fix hit the plugin gives it actually cause an error since it is not providing an extension for the `collectionType` `ConfigInput`

<img width="912" alt="image" src="https://user-images.githubusercontent.com/79875862/158894567-647e719b-d66f-41e6-8184-ed8b63ff227b.png">

The same situation happens when using it on a typical query with no graphql federation.

Can you please help, thanks!

**Comment by srinivasankavitha** [comment]
Thanks for reporting this, will look into a fix. In the meantime, you could try suppressing the hint in IntelliJ.

**Comment by vasquez-csdisco** [comment]
Much appreciated! 🙌🏼

**Comment by srinivasankavitha** [comment]
Fix in the latest release which will be available in the next week or so.

**Comment by vasquez-csdisco** [comment]
> Fix in the latest release which will be available in the next week or so.

that is awesome! thank you!
