### ISSUE TITLE
False positive hint about schema mismatch on final input argument parameters

### ISSUE THREAD

**Issue by pschyma** [Netflix/dgs-intellij-plugin#48]
Making a method parameter final that is also annotated with `@InputArgument` creates a warning hint about not matching the schema. Removing the final modifier removes the hint. 

![image](https://user-images.githubusercontent.com/2489928/192953415-27ec35b6-82ee-4ce1-a34a-8406e07335cc.png)

**Comment by srinivasankavitha** [comment]
Thanks for reporting. Please suppress the warning for the time being while we work on a fix for this.
