### ISSUE TITLE
Update the plugin to support IntelliJ IDEA 2023.1+

### ISSUE THREAD

**Issue by mamuf** [Netflix/dgs-intellij-plugin#56]
The latest plugin version (1.2.5) is marked as incompatible with the just-released IntelliJ IDEA 2023.1.

Thanks!

**Comment by sothychan** [comment]
https://github.com/Netflix/dgs-intellij-plugin/pull/55 -- should fix it.  Do we have an estimated release day?  Thanks!

**Comment by srinivasankavitha** [comment]
Yes, I will create a new release today. It should be available for update
in a few days.

**Comment by srinivasankavitha** [comment]
The latest release is available now for download.
