### ISSUE TITLE
Navigation from code to schema and vice versa doesn't show up with GraphQL Config file(s) present

### ISSUE THREAD

**Issue by mamuf** [Netflix/dgs-intellij-plugin#65]
Hi, I have multiple gradle projects in a single IntelliJ IDEA project, one is the main app and includes the master GraphQL schema files and uses DGS to implement the API, and another is a client library that uses Apollo to fetch the schema from the app to generate the source files to be used by the client lib.

I'd like to keep both of these inside a single IDEA project, but it seems that the GraphQL plugin the DGS plugin depends on only supports a single schema inside IDEA project, unless you add a GraphQL Config file (e.g., graphql.config.yml). Basically, unless I add these config files to all the GraphQL schema instances, the in-editor navigation tends to jump to the wrong GraphQL files.

Now, when I specify the different schemas via the GraphQL config files, the GraphQL plugin works correctly, but the DGS plugin stops working. Basically, the DGS icons you can normally click to navigate from the schema file to Java/Kotlin source code for a given query/mutation simply disappear from the editor. Once I remove the GraphQL config files, they appear again, but that leads to the issues described in the previous paragraph.

I'm not sure where exactly the problem lies, so I'm trying to report it here first. Thanks in advance!

**Comment by coleturner** [comment]
Hey @mamuf thank you for sharing this issue. It sounds like the issue you are running into is happening when there are multiple modules in a project and a GraphQL config file is used, resulting in code navigation not working as expected.

We will look into this issue and return with what we find.

**Comment by coleturner** [comment]
We believe the issue to have been due to how the DGS is recognized within multi-module projects. The fix was just released in the v1.3.0, please give that a try and let us know if there's any further trouble.
