### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by esfomeado** [Netflix/dgs-intellij-plugin#68]
When version 1.3.0 is going to be released?

Thanks

**Comment by coleturner** [comment]
1.3.0 was released three weeks ago:
https://github.com/Netflix/dgs-intellij-plugin/releases/tag/v1.3.0

**Comment by esfomeado** [comment]
But is not available on Intellij

**Comment by coleturner** [comment]
Apologies for the confusion on my end, there were some issues publishing the plugin. It is resolved now:
https://github.com/Netflix/dgs-intellij-plugin/actions/runs/5348736594

We have just published the plugin, it make take 24-48 hours for IntelliJ to approve the update.

**Comment by esfomeado** [comment]
Thanks.
