### ISSUE TITLE
Plugin is incompatible with the Kotlin plugin in K2 mode

### ISSUE THREAD

**Issue by hpuac** [Netflix/dgs-intellij-plugin#92]
With the IntelliJ 2024.1 release, Jetbrains introduced the K2 mode in Alpha state.
It just got into the Beta state with the 2024.2 release.
Soon with the upcoming 2024.3 release the mode will be enabled by default.

The DGS IntelliJ plugin is currently not compatible with the Kotlin plugin in K2 mode.
It would be amazing if you could have a look and add compatibility.

See: https://blog.jetbrains.com/idea/2024/08/meet-the-renovated-kotlin-support-k2-mode/

Also see:
<img width="415" alt="Screenshot 2024-08-08 at 13 48 54" src="https://github.com/user-attachments/assets/db64f2f4-325c-4992-a1db-8f735001e06b">

**Comment by vigenere23** [comment]
+1. This is still in beta tho, so plenty of times to support it i guess. But this will likely be the the next default mode used by IntelliJ. Is it planned in the roadmap?

**Comment by iuliiasobolevska** [comment]
K2 support was added in v1.4.1 released 2 weeks ago. Thank you for the report!

**Comment by iuliiasobolevska** [comment]
Closing the thread based on:
```
Version 1.4.2 of the DGS plugin has been approved by JetBrains and is now publicly available at the following link: https://plugins.jetbrains.com/plugin/17852-dgs/versions/stable/619401.
```
